name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Copy files to EC2
      run: |
        scp -r -o StrictHostKeyChecking=no ./* ec2-user@3.86.183.72:/home/ec2-user/Dreams-backend/

    - name: SSH and Deploy
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@3.86.183.72 <<EOF
        cd /home/ec2-user/Dreams-backend/src
        npm install --omit=dev
        pm2 start server.js --name Dreams-backend --env MONGO_URI="mongodb+srv://dream:dream123@cluster0.oynhj.mongodb.net/Dreams" --env JWT_SECRET="your_jwt_secret_key" --env PORT="5000" --update-env
        EOF
